# Generated by Django 3.0.5 on 2021-01-13 10:21

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicants',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidatename', models.TextField(default='', max_length=100)),
                ('appliedfor', models.TextField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.TextField(default='')),
                ('resumeurl', models.TextField(default='')),
            ],
        ),
    ]
