# Generated by Django 3.0.5 on 2021-07-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210722_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientenquiries',
            old_name='activated',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='clientenquiries',
            old_name='deactivated',
            new_name='inactive',
        ),
    ]
