# Generated by Django 3.0.5 on 2021-06-24 12:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210624_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('isSales', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isHR', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
