# Generated by Django 3.0.5 on 2021-07-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210722_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usersname',
            field=models.CharField(max_length=100),
        ),
    ]
